### PR TITLE
Fixed get version code for version 1.183

### PR DESCRIPTION
**Pull request by danielfelipesartorio**

### CODE REVIEW

**Comment by Th3C0D3R** [comment]
Its not good to include things which will change with each version. Thats why i didn't include this number.

**Comment by Th3C0D3R** [comment]
I don't know why it doesn't work but thats not why 😅

**Comment by Th3C0D3R** [comment]
Wait 😂
I miss read the PR... its accepted

**Comment by danielfelipesartorio** [comment]
Sorry, i'm not great with english grammar haha

**Comment by Th3C0D3R** [comment]
No just the changes in code i missread 😅

**Pull request merged**
